name = "cloudflare-docker-proxy"
workers_dev = true
main = "src/index.js"
compatibility_date = "2021-12-07"
routes = [
    { pattern = "docker.1111119.xyz", custom_domain = true },
    { pattern = "quay.1111119.xyz", custom_domain = true },
    { pattern = "gcr.1111119.xyz", custom_domain = true },
    { pattern = "k8s-gcr.1111119.xyz", custom_domain = true },
    { pattern = "k8s.1111119.xyz", custom_domain = true },
    { pattern = "ghcr.1111119.xyz", custom_domain = true },
    { pattern = "cloudsmith.1111119.xyz", custom_domain = true },
]
[dev]
ip = "0.0.0.0"
port = 8787
local_protocol="http"
upstream_protocol="https"

[vars]
MODE="production"
LOCAL_ADDRESS=""
TARGET_UPSTREAM=""

[env.dev.vars]
MODE="debug"
LOCAL_ADDRESS="http://192.168.10.102:8787"
TARGET_UPSTREAM="https://registry-1.docker.io"
